name: Sync Upstream Repository

# 触发条件：每6小时自动运行，允许手动触发
on:
  schedule:
    - cron: '0 2,8,14,20 * * *'  # 每天02:00, 08:00, 14:00, 20:00 (UTC) 运行
  workflow_dispatch:  # 允许手动触发

env:
  TZ: Asia/Shanghai  # 设置时区为上海

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      # 检出当前仓库代码

    - name: Configure Git
      run: |
        git config --global user.name "880824"   # 替换为您的 GitHub 用户名
        git config --global user.email "mengzehe@gmail.com"  # 替换为您的 GitHub 邮箱

    - name: Add Upstream Remote
      run: |
        git remote add upstream https://github.com/cmliu/CF-Workers-SUB.git  # 原始仓库URL
        git fetch upstream  # 拉取上游仓库更改
        git checkout main   # 切换到主分支 (若非 main 分支，请替换为正确的分支名)
        git merge upstream/main --no-edit  # 合并来自上游仓库的更改，自动提交

    - name: Push Changes
      run: |
        DATE=$(date +"%Y-%m-%d %H:%M:%S")
        git commit -m "拉取更新： $DATE"
        git push origin main  # 将合并后的更改推送到自己的仓库

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的内置身份验证 Token
